### ISSUE TITLE
Optimize Images [Easy]

### ISSUE THREAD

**Issue by ajiteshr7** [JMI-CSI/jmi-csi.github.io#13]
A nice and easy fix for all those looking for a PR.

**Comment by rafa-acioly** [comment]
i can do it! 😄

**Comment by rafa-acioly** [comment]
#14 🎉 🎈

**Comment by iharsh234** [comment]
@rafa-acioly whenever you hava a PR , for an issue please use keyword like `closes #(id)`.
You can read more about it [here](https://help.github.com/articles/closing-issues-using-keywords/)
